# Generated by Django 2.2.3 on 2019-07-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chewy', '0002_historic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historic',
        ),
    ]
